<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Saved successfully</name>
   <tag></tag>
   <elementGuidId>c8bff1a6-b928-4a09-aebc-401b14595d44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#swal2-html-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='swal2-html-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b3829df3-a975-4b9b-bd7d-d81fd308be2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>swal2-html-container</value>
      <webElementGuid>e90e588b-4bba-4c83-869c-5a68965b6444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>swal2-html-container</value>
      <webElementGuid>106ecc96-9ff5-44b6-adc2-cd418a9e36b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Saved successfully.</value>
      <webElementGuid>d67db8b4-04da-4af9-874d-09c22fd86b38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;swal2-html-container&quot;)</value>
      <webElementGuid>fd64c732-6e11-4f2c-952a-1cbd83cdc241</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='swal2-html-container']</value>
      <webElementGuid>ce1ea92d-33a9-4829-a314-7007ec4c0794</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/following::div[6]</value>
      <webElementGuid>ddcc2b0b-b9a5-4b57-9762-f4428049f906</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/following::div[8]</value>
      <webElementGuid>03866720-5026-4027-8375-7cfb11bc8fdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[1]/preceding::div[5]</value>
      <webElementGuid>b089d70f-faa6-4377-9990-6b663c40c6df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/preceding::div[5]</value>
      <webElementGuid>ecbd54b6-587c-405f-be25-173fd56f7e16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Saved successfully.']/parent::*</value>
      <webElementGuid>41bd84b8-d31f-4adb-b9e4-5e7b6eeb7055</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]</value>
      <webElementGuid>87d469f5-065d-4d4f-a94c-db7514acd197</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'swal2-html-container' and (text() = 'Saved successfully.' or . = 'Saved successfully.')]</value>
      <webElementGuid>3b692de4-611d-46c4-b871-60543b561f83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
