<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_300</name>
   <tag></tag>
   <elementGuidId>7e5de711-ee6f-48b3-9ab1-28ca86fd0c8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cell-3-undefined</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cell-3-undefined']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>11310c26-3523-493d-b031-ffacb4c72712</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cell-3-undefined</value>
      <webElementGuid>d213a6f9-b608-4f71-aac6-878efb989013</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-column-id</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>4df1a3d5-7737-4b43-8fd7-60f67022d42e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>cell</value>
      <webElementGuid>2db42c80-a3d1-4607-b11a-daa3874019fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-hLBatu sc-eDvShL sc-jSVask gDWDBl cPssfJ igdpVR rdt_TableCell</value>
      <webElementGuid>762ec92a-2c36-458d-b768-723bf9c37ac1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tag</name>
      <type>Main</type>
      <value>allowRowEvents</value>
      <webElementGuid>8f7f85cc-8ed7-42ba-8fc0-cccff4849c17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>9556bfee-1768-4fec-af2a-c4031fbdadcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cell-3-undefined&quot;)</value>
      <webElementGuid>638bf726-32dc-4510-b126-43e260449dcc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='cell-3-undefined']</value>
      <webElementGuid>fd6edcb6-3636-4701-8d89-c56fa27b89e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='row-0']/div[3]</value>
      <webElementGuid>4d914d74-5eac-4cfa-a190-0f49ea688675</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DATE'])[1]/following::div[7]</value>
      <webElementGuid>965800b6-9607-4b6c-877f-2dd9c1017773</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REASON CODE'])[1]/following::div[10]</value>
      <webElementGuid>ac6670e9-b306-4b84-99e5-87a6c5188cff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rows per page:'])[1]/preceding::div[4]</value>
      <webElementGuid>6724d86f-eac6-49f5-a9a9-7b172026c780</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/preceding::div[7]</value>
      <webElementGuid>4750dcc4-6e20-4dfb-b4e8-f6db359eb477</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]</value>
      <webElementGuid>1c9fb0f6-4f19-4267-826d-9f55a1783b8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'cell-3-undefined' and (text() = '300' or . = '300')]</value>
      <webElementGuid>ac1f2246-8a62-4cca-aa5e-27d9be3e1a81</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
