<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_01262026 113000</name>
   <tag></tag>
   <elementGuidId>726fa5cd-544b-4bd6-a408-75df654fc16b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cell-4-undefined</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cell-4-undefined']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f7edb6e1-034f-4008-8582-2998957f661f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cell-4-undefined</value>
      <webElementGuid>dc875233-1017-408b-9015-f84783fddbc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-column-id</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>0b6e3205-0bb2-46c0-98bb-e3256c1db956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>cell</value>
      <webElementGuid>f0d8bbdf-91a8-4910-97ab-b828958042b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-hLBatu sc-eDvShL sc-jSVask gDWDBl cPssfJ igdpVR rdt_TableCell</value>
      <webElementGuid>300a687d-10da-487b-98f6-74a1a910cfe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tag</name>
      <type>Main</type>
      <value>allowRowEvents</value>
      <webElementGuid>c7cdf9d5-8019-46f4-80d9-f398ea06009e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>01/26/2026 11:30:00</value>
      <webElementGuid>3d0bb063-b73b-4250-b0bf-750887f2f74b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cell-4-undefined&quot;)</value>
      <webElementGuid>3f3e609d-f8f2-4054-ac52-da3a9dac61a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='cell-4-undefined']</value>
      <webElementGuid>ee0fc279-1314-4a2c-b1dc-c1539deddd5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='row-0']/div[4]</value>
      <webElementGuid>a6459ac8-793e-4067-bc3f-1a9f4e023ec9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DATE'])[1]/following::div[9]</value>
      <webElementGuid>6a2ef585-ed0e-49d7-93ff-f3d8c017e49e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REASON CODE'])[1]/following::div[12]</value>
      <webElementGuid>5f7983eb-150d-40a9-9fc8-819560764c41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rows per page:'])[1]/preceding::div[2]</value>
      <webElementGuid>fb84250b-d65c-4b96-a429-6678acd54cba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/preceding::div[5]</value>
      <webElementGuid>139d70ba-b730-4cc6-9999-e3b1160b196d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[4]</value>
      <webElementGuid>c8ae9e73-89f6-40c9-b6e1-b6c5cd8ed053</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'cell-4-undefined' and (text() = '01/26/2026 11:30:00' or . = '01/26/2026 11:30:00')]</value>
      <webElementGuid>855bbc53-0d5f-41bc-80de-188d81c2d92b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
