<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_15</name>
   <tag></tag>
   <elementGuidId>6cbefd3d-189d-475c-8100-bc4ef841d7fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cell-2-undefined</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cell-2-undefined']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4eed169f-23d0-4a96-890a-cdb200bed68d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cell-2-undefined</value>
      <webElementGuid>ba976d59-8ec3-4e14-8179-79bf68f91743</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-column-id</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>8e68d25d-953e-403e-b551-1b6815ae3bbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>cell</value>
      <webElementGuid>b4776931-f00f-4a00-ad09-239f82f45e09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-hLBatu sc-eDvShL sc-jSVask gDWDBl cPssfJ igdpVR rdt_TableCell</value>
      <webElementGuid>efc6fa7f-4c3f-4d26-88a4-71085fde26ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tag</name>
      <type>Main</type>
      <value>allowRowEvents</value>
      <webElementGuid>6f89a343-7227-4492-8fbd-b290c0ef4e0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>263659d8-7f40-4754-804a-dfb59d714850</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cell-2-undefined&quot;)</value>
      <webElementGuid>9d5b7286-0d1e-4b8a-8837-3fadba856cf9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='cell-2-undefined']</value>
      <webElementGuid>e3d415c7-775e-44f9-a732-7b7f43dc6009</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='row-0']/div[2]</value>
      <webElementGuid>285ac220-904a-43ba-877d-0a8977832fec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DATE'])[1]/following::div[5]</value>
      <webElementGuid>e721572c-eb8a-4f31-881e-f7755f2c2049</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REASON CODE'])[1]/following::div[8]</value>
      <webElementGuid>67835609-dd53-46b0-9e81-41230305b227</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rows per page:'])[1]/preceding::div[6]</value>
      <webElementGuid>078267ea-b524-4a1f-999d-85e8ee8c6e96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/preceding::div[9]</value>
      <webElementGuid>b5f23f7d-b28e-482d-ae7f-1b7d30c1cd17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]</value>
      <webElementGuid>b2e1c846-588a-46ef-bff4-f5b81b0e5922</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'cell-2-undefined' and (text() = '15' or . = '15')]</value>
      <webElementGuid>51ce51bb-6e2c-4ea2-940c-2babe0c54eb2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
