<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_HAWB</name>
   <tag></tag>
   <elementGuidId>271f7f64-37ed-43bb-9d40-9634193c3966</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.sc-ipEzrc:nth-child(1) .sc-csuRvn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' sc-ipEzrc ') and (position() = 1)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' sc-csuRvn ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c336845a-795b-4ea5-bfdc-5b06675452e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-column-id</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>931e906e-b8e5-4305-b464-4a388f0dd452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sort-id</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>9f3d534e-ba19-4ca9-a7cb-86502c27c422</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>columnheader</value>
      <webElementGuid>6c96ee3b-1627-418f-b26b-756246f34853</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3db3b1fd-0399-4425-a65d-365f119cec0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-csuRvn ilhcix rdt_TableCol_Sortable</value>
      <webElementGuid>8659f289-214a-4959-aa5d-b4925e9d832e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>HAWB</value>
      <webElementGuid>b53c0173-3ea5-4da6-9750-a0e4a4bd5421</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-4901af2dc2dba30b380560d536338ed3</value>
      <webElementGuid>5441dbf2-874d-4ca5-ae86-f97bc4496115</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' sc-ipEzrc ') and (position() = 1)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' sc-csuRvn ')]</value>
      <webElementGuid>4980a9bb-9990-4a21-a19b-9ef51d1d5539</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' sc-ipEzrc ') and (position() = 1)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' sc-csuRvn ')]</value>
      <webElementGuid>569fb1e7-8027-470b-b122-8c3ca14b14ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'HAWB' or . = 'HAWB')]</value>
      <webElementGuid>b25a54f3-3c8c-4651-93a6-1f470541e9cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
