<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_728456401371</name>
   <tag></tag>
   <elementGuidId>d89ad6ef-f51d-4abb-8b09-21cf783752ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cell-1-undefined</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cell-1-undefined']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d0ebaca7-fac1-4382-b5eb-d7e6fd56618d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cell-1-undefined</value>
      <webElementGuid>73e475b9-a72e-49d4-905a-daf80c91d2cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-column-id</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>bbf7b74c-2b25-4402-b9c1-c3308806979e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>cell</value>
      <webElementGuid>dfd1ebf5-f451-4286-9818-52cb04bf7985</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-hLBatu sc-eDvShL sc-jSVask gDWDBl cPssfJ igdpVR rdt_TableCell</value>
      <webElementGuid>afb03296-caae-4877-9f59-d6792b319f3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tag</name>
      <type>Main</type>
      <value>allowRowEvents</value>
      <webElementGuid>d89733e1-5e42-49b8-8d2b-8d5e7a5f70f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>728456401371</value>
      <webElementGuid>169546f9-cd60-441d-ba1d-975cc9610466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cell-1-undefined&quot;)</value>
      <webElementGuid>ead8e1b3-0d8a-4c68-ac63-d8b63d8c3b85</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='cell-1-undefined']</value>
      <webElementGuid>78131423-d3bf-491b-baed-9378f7acf6c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='row-0']/div</value>
      <webElementGuid>f2fb8148-6eba-4d1f-98e6-d552f6e8fe1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DATE'])[1]/following::div[3]</value>
      <webElementGuid>3e71975d-6619-416a-97a4-ff65a173dcc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REASON CODE'])[1]/following::div[6]</value>
      <webElementGuid>dca77098-46d1-4ed1-b487-10a04bf0a70a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rows per page:'])[1]/preceding::div[8]</value>
      <webElementGuid>679bec16-9446-4515-a751-50bd749c6a1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/preceding::div[11]</value>
      <webElementGuid>18498483-85a2-4bf6-bd78-d95febe36a4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/div/div[2]/div/div</value>
      <webElementGuid>7e72bc8c-30df-4531-a7a0-507be94557bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'cell-1-undefined' and (text() = '728456401371' or . = '728456401371')]</value>
      <webElementGuid>b7db3d6b-868e-4d7a-9a05-0cc31f781456</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
