<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Username</name>
   <tag></tag>
   <elementGuidId>06f148e4-ce53-4cd1-9a74-8a7ee7f3eea2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#LOGIN_USERNAME</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @id = 'LOGIN_USERNAME' and @placeholder = 'Username']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'LOGIN_USERNAME']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Username&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b1a41168-6974-453e-871d-47d9b3cae11b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cc21dc0f-819a-4c65-9ef0-d04309f89ac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control block w-full px-4 py-2 text-xl font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none</value>
      <webElementGuid>eaff8bc1-e91c-4c57-b7d7-13c07968a8cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LOGIN_USERNAME</value>
      <webElementGuid>3afb3d75-bc16-46ca-8b70-41a6bd5cf7be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Username</value>
      <webElementGuid>62b52005-3697-4f62-836f-d8be51cfe9bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-7b6d75c52adf231b47d7279dfa5a959f</value>
      <webElementGuid>2ca71414-82eb-45f0-8b06-56fb6d28be41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'LOGIN_USERNAME']</value>
      <webElementGuid>3e8bf2f8-aaec-4d29-854b-7ad375421562</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'LOGIN_USERNAME']</value>
      <webElementGuid>0a6753eb-1cd8-44d8-816d-52473b81642e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'LOGIN_USERNAME' and @placeholder = 'Username']</value>
      <webElementGuid>ad6ab0a8-9d0f-4112-b47a-4d32500c24f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
